
birds: birdtest.cpp Duck.h Goose.h Owl.h Ostrich.h Kiwi.h Penguin.h WalkingBird.h FlyingBird.h Bird.h
	g++ -Wall birdtest.cpp -o birdtest
#	g++ -Wall birdtes.cpp -o birds -frtti

clean:
	rm -f birdtest *~ *# *.o
